#### **NumPy Array Basics**

In [2]:
import numpy as np
import pandas as pd

##### Numpy Arrays are fixed-sized containers </br> - Store only 1 datatype, (mixed are object -string) </br> - 1 dimensional or multidimensional </br> - Array elements can be modified, but array size cannot change

In [3]:
## List to numpy array example
# List
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
# np function will convert list as numpy array
sales_array = np.array(sales, dtype = np.int64)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325],
      dtype=int64)

##### Numpy Arrays Key Properties </br> - ndim: Number of dimensions (axes) in array </br> - shape: size of array for each dimension </br> - size: total number of elements in array </br> - dtype: data type of elements in array

In [4]:
# display type of array
type(sales_array)
# numpy arrays are ndarray Python Data type: stands for n-dimensional array

numpy.ndarray

In [5]:
# display different aspects of numpy sales_array
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")

ndim: 1
shape: (10,)
size: 10
dtype: int64


In [6]:
# ndim: 1      -> Array has 1 dimension
# shape: (10,) -> Dimension has a size of 10
# size: 10     -> Array has 10 elements in total
# dtype: int64 -> Elements stored as 64-bit Integers

In [7]:
# Original lists has nested elements which means [[],[]] is the format
# nested lists must be of equal length
sales2d = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
# np function will convert nested list as numpy array as dtype4 int64
sales2d_array = np.array(sales2d, dtype = np.int64)
sales2d_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]], dtype=int64)

In [8]:
# display different aspects of numpy sales2d_arrays 
print(f"ndim: {sales2d_array.ndim}")
print(f"shape: {sales2d_array.shape}")
print(f"size: {sales2d_array.size}")
print(f"dtype: {sales2d_array.dtype}")

ndim: 2
shape: (2, 5)
size: 10
dtype: int64


In [9]:
# ndim: 2      -> Array has 2 dimension
# shape: (2, 5)-> First Dimension has size 2 (rows), Second Dimension has Size of 5 (columns)
# size: 10     -> Array has 10 elements in total
# dtype: int64 -> Elements stored as 64-bit Integers

In [10]:
# Create 1d numpy array using range function
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [11]:
# Create 1d numpy array using range function
array2d = np.array([range(5), range(5)])
array2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [12]:
np.array(['I', 'Love', 'Python'])
# displays dtype as '<U6' because strings are max of 6 characters

array(['I', 'Love', 'Python'], dtype='<U6')

### **NumPy Array Creation**

##### <b> Alternative to Converting lists is to create arrays using functions</b></br> - ones: Creates an array of ones of a given size, as float by default </br> &nbsp;&nbsp; np.ones((rows,cols),dtype) </br> - zeros: Creates an array of zeros of a given size, as float by default </br> &nbsp;&nbsp; np.zeros((rows,cols),dtype) </br> - arange: creates an array of integers with a start, stop, step size (only stop is required, and not included) </br> &nbsp;&nbsp; np.arange(start, stop, step) </br> - linspace: creates an array of floats with a start, stop value where the step will be decided by the quantity of n elements (stop value is included) </br> &nbsp;&nbsp; np.linspace(start, stop, n) </br> - reshape: changes an array into the specified dimension (if compatible) </br> &nbsp;&nbsp; np.array.reshape(rows,cols)

In [ ]:
# np.ones((rows,cols),dtype)
np.ones(4,)

array([1., 1., 1., 1.])

In [ ]:
# np.zeros((rows,cols),dtype)
np.zeros((2, 5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# np.arange(start,stop,step)
# default start = 1, default step = 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# np.arange(start,stop,step)
# set start, set step
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [ ]:
# np.linspace(start,stop,n)
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
# np.array.reshape(rows,cols)
np.arange(1, 9, 2).reshape(2, 2)

array([[1, 3],
       [5, 7]])

In [ ]:
# np.ones((rows,cols),dtype) can have dtype explicitly set instead of default float
np.ones(4,'int') # or use np.ones(4, dtype='int')

array([1, 1, 1, 1])

In [ ]:
# np.zeros((rows,cols),dtype)
np.zeros(100, 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# with reshape for np.zeros(100) the reshape values must be multiply by each other to equal 100 to be compatible
reshapedemo = np.zeros(100, 'int')
reshapedemo.reshape(5,20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# with reshape for np.zeros(100) the reshape values must be multiply by each other to equal 100 to be compatible
reshapedemo.reshape(2, 50)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

In [ ]:
# np.linspace(start,stop,n) for evenly spaced intervals
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

##### <b> Random Number Generation</b></br> Can create random number arrays from variety of distributions using numpy functions and methods </br> - default_rng: Creates a random number generator and seed is used for reproducibility </br> &nbsp;&nbsp; np.default_rng(seed) </br> - random: returns n random numbers from a uniform distributions between 0 and 1 </br> &nbsp;&nbsp; rng.random(n) </br> - normal: returns n random numbers from a normal distribution with a given mean and standard deviation </br> &nbsp;&nbsp; rng.normal(mean,stdev,n)

In [ ]:
# Import the default random number generator from NumPy.
from numpy.random import default_rng

# Initialize the random number generator with a specific seed for reproducibility.
rng = default_rng(12345)

# Generate an array of 10 random numbers between 0 and 1.
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [ ]:
rng.integers(0, 10, 100)

array([7, 2, 9, 9, 7, 6, 1, 0, 2, 4, 0, 8, 4, 6, 2, 3, 1, 7, 7, 2, 7, 0,
       3, 1, 7, 3, 4, 4, 4, 2, 5, 8, 4, 1, 0, 1, 0, 0, 1, 5, 8, 8, 6, 6,
       3, 9, 6, 7, 7, 8, 7, 9, 5, 5, 2, 9, 5, 4, 3, 2, 6, 4, 5, 6, 8, 3,
       6, 9, 4, 2, 2, 3, 6, 2, 8, 3, 0, 0, 0, 6, 3, 2, 6, 0, 5, 6, 0, 1,
       3, 3, 9, 4, 6, 1, 8, 2, 7, 4, 4, 4], dtype=int64)

In [ ]:
# Create a random number generator seeded with 12345 for consistent results.
rng = default_rng(12345)

# Set the mean and standard deviation for the normal distribution.
mean, stddev = 5, 1

# Generate an array of 10 random numbers from a normal distribution with specified mean and stddev.
random_normal = rng.normal(mean, stddev, size=10)
random_normal


array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [ ]:
rng.normal(50, 5, 10)

array([49.64364597, 52.37024865, 47.92573119, 50.4885825 , 41.79791082,
       45.71370588, 53.44140894, 44.22735208, 53.25226195, 43.05820024])

##### <b> Indexing and Slicing Arrays One dimensional arrays </b></br> - array[index]: indexing to access a single element (0-indexed)</br> - array[start:stop:step size]: slicing to access a series of elements (stop is not included)

In [ ]:
# generate 1 dimensional array
product_array = np.array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks', 'beverages', 'coffee', 'tea', 'spices'])

product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [ ]:
# display index 1 (element 2)
print(product_array[1])
# display last index (last Element)
print(product_array[-1])

vegetables
spices


In [ ]:
# display first 5 elements of array
product_array[:5]

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
# displays element 6 as start, with no stop,  using 2 steps (grabs every other element, until end of array)
product_array[5::2]

array(['snacks', 'coffee', 'spices'], dtype='<U10')

##### <b> Indexing and Slicing Arrays Two dimensional arrays </b></br> - array[row index, column index]: indexing to access a single element (0-indexed)</br> - array[start:stop:step size, start:stop:step size]: slicing to access a series of elements (stop is not included)

In [ ]:
# reshape 1 dimensional array to become 2 dimensional array
product_array2d = product_array.reshape(2, 5)

product_array2d

array([['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [ ]:
# single element indexing for 'coffee' at row index 1 and column index 2 of the 2D array
product_array2d[1,2]

'coffee'

In [ ]:
# display all rows, but only a slice of the columns at the third element
product_array2d[:, 2:]

array([['cereal', 'dairy', 'eggs'],
       ['coffee', 'tea', 'spices']], dtype='<U10')

In [ ]:
# display second row, and all columns (indicated by the comma)
product_array2d[1:, :]

array([['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [ ]:
# grab first 2 rows of array -> start at first row and stop at Second row without step
product_array2d[:2, :]

array([['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [ ]:
# grab the entire first column. [all rows:, first column for each row] 
product_array2d[0:, 0]

array(['fruits', 'snacks'], dtype='<U10')

In [ ]:
# grab second element of second row
product_array2d[1,1]

'beverages'

### <b> Array Operations </b></br>

##### <b> Arithmetic operators can be used to perform array operations </b></br> - Array operations are applied via vectorization and broadcasting which eliminates need to loop through arrays elements

In [ ]:
# generate nested list
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]

# convert in np array
sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
# with + 2 -> 2 is added to each element of the np array
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [ ]:
# Assign all elements of first row to quantity
quantity = sales_array[0, :]
# Assign all elements of second row to price
price = sales_array[1, :]

# corresponding elements are multiplied together
quantity * price

array([     0,   9135,  95480,      0, 168350])

In [ ]:
# generate random number generator with 616 seed
rng = np.random.default_rng(616)

# assign random integers to inventory variable start 0, end 100, 10 random grabbed
inventory = rng.integers(0, 100, 10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [ ]:
# minus 24 from each array element
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [ ]:
# view half the inventory amounts -> divide 2 from each array element
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [ ]:
# create 11 random price values (which will be between 0 and 1) so multiple by 10 and then round to 2 decimal places
# price = (rng.random(11)*10).round(2)
# this operation will have error because array shapes do not match 10 vs 11
# price * inventory

In [ ]:
# create 10 random price values (which will be between 0 and 1) so multiple by 10 and then round to 2 decimal places
price = (rng.random(10)*10).round(2)

price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [ ]:
# operations can occurs between arrays as long as they are the same shape
# price * inventory

# the is a sum method to easily add all element values
(price * inventory).sum().round(2)

2520.47

In [ ]:
# np arrays can be cast to a list
inventory_list = list(inventory)
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

##### <b> Filtering Arrays </b></br> You can filter arrays by indexing them with a logical test </br> - Only the array elements in positions where the logical test returns True are returned

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
# perform logical test in NumPy array will return a Boolean array with the results of logical test on each array element

# logical test to see which array elements do not equal zero
sales_array != 0

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [ ]:
# assign the True values to new array (using boolean filter on array to pull True values depending on logical condition) assigns elements that have a value that isn't zero
actual_sales_array = sales_array[sales_array != 0]
actual_sales_array

array([   5,  155,  518, 1827,  616,  317,  325])

##### Can be filtered with multiple logical tests using & (and) | (or)

In [ ]:
multiple_logic1 = sales_array[(sales_array == 616) | (sales_array < 100)]
multiple_logic1

array([  0,   5,   0,   0, 616])

In [ ]:
multiple_logic2 = sales_array[(sales_array > 100) & (sales_array < 500)]
multiple_logic2

array([155, 317, 325])

##### Multiple logical tests can be added to variable and used as Boolean mask

In [ ]:
# can create variable that will handle the boolean mask for filtering multiple logic conditions
mask1 = ((sales_array < 1500) & (sales_array > 500)) | (sales_array == 0)

# apply boolean mask variable to array
multiple_logic_mask = sales_array[mask1]
multiple_logic_mask

array([  0,   0, 518,   0, 616])

##### Values from One array can be used to filter another array (if arrays are same shape)

In [ ]:
# call multiple_logic_mask
multiple_logic_mask

array([  0,   0, 518,   0, 616])

In [ ]:
# creation of product array
product_array = np.array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
# array to be filtered[array used as filter with logic]
# this will filter out values that are zero from the array
filtered_product = product_array[multiple_logic_mask > 0]
filtered_product

array(['cereal', 'eggs'], dtype='<U10')

In [ ]:
# another boolean mask example
demo_array = np.arange(0,20)
demo_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# string array 'even', 'odd' 10 ten times to match demo_array shape
even_odd = np.array(['even', 'odd']*10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [ ]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [ ]:
# sets elements in demo_array to 0 where the condition even_odd != 'odd' evaluates to true.
demo_array[even_odd != 'odd'] = 0
demo_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

##### <b> Where Function </b></br> - where() NumPy function performs logical test and returns a given value if test is True and returns a value if test is False </br> &nbsp;&nbsp; np.where(logical test, Value if True, Value if False)

In [ ]:
# creation of inventory array
inventory_array = np.array([12, 102, 18, 0, 0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [ ]:
# calling product array
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
# using NumPy where() function to filter array
# np.where(logical test, Value if True, Value if False)

np.where(inventory_array > 0, 'In Stock', 'Out of Stock')

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
# using NumPy where() function to filter array to return value and value from filtered Array
# np.where(logical test, Value if True, Value if False)

np.where(inventory_array > 0, 'In Stock', product_array)

array(['In Stock', 'In Stock', 'In Stock', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
# chaining .np.where() conditions
demo_array1 = np.arange(0,20)
demo_array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# chaining .np.where() conditions
# label elements in demo_array as 'even' if divisible by 2, 'odd' otherwise, and replaces elements with the value 9 if they're equal to 9
np.where(demo_array % 2 == 0, 'even', np.where(demo_array == 9, 9, 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U11')

##### Modify Array values - not used often as data analyst

In [ ]:
# copy array values to new array
modify_array = multiple_logic_mask.copy()
# array([  0,   0, 518,   0, 616])

# modify values is done by calling the index and assigning value
modify_array[3] = 3
modify_array
# third index is changed to 3
#array([  0,   0, 518,   3, 616])


array([  0,   0, 518,   3, 616])

##### <b>Array Aggregation Methods </b></br> Let you Calculate Metrics </br> &nbsp;&nbsp; sum, mean, max, min, stddev

In [ ]:
# call sales_array
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

#### NumPy Aggregation Functions

| Method                       | Description                                    |
|------------------------------|------------------------------------------------|
| `sum()`                      | Sum of all the elements in the array.          |
| `prod()`                     | Product of all the elements in the array.      |
| `min()`                      | Minimum value among the elements in the array. |
| `max()`                      | Maximum value among the elements in the array. |
| `mean()`                     | Mean of the array elements.                    |
| `median()`                   | Median of the array elements.                  |
| `std()`                      | Standard deviation of the array elements.     |
| `var()`                      | Variance of the array elements.                |
| `percentile()`               | Specific percentile of the array elements. Use arguments like 25 for the 25th percentile, etc. |
| `sqrt()`                     | Square root of each element in the array.      |

**Note**: To apply `median()`, `percentile()`, and `sqrt()`, use NumPy directly e.g., `np.median(sales_array)`, `np.percentile(sales_array, 25)`, and `np.sqrt(sales_array)`.


In [ ]:
# these return the aggregated values from all values in the array
print(f'Array Elements Sum: {sales_array.sum()}')
print(f'Array Elements Product: {sales_array.prod()}')
print(f'Array Elements Minimum: {sales_array.min()}')
print(f'Array Elements Maximum: {sales_array.max()}')
print(f'Array Elements Mean: {sales_array.mean()}')
print(f'Array Elements Median: {np.median(sales_array)}')
print(f'Array Elements Standard Deviation: {sales_array.std()}')
print(f'Array Elements Variance: {sales_array.var()}')
# Percentile function requires the Percentile amount 25th, 75th percentile as argument
print(f'Array Elements 25th Percentile: {np.percentile(sales_array, 25)}')
print(f'Array Elements 75th Percentile: {np.percentile(sales_array, 75)}')
# square root function does each element of array
print('Array Elements Square Root:') 
np.sqrt(sales_array)

Array Elements Sum: 3763
Array Elements Product: 0
Array Elements Minimum: 0
Array Elements Maximum: 1827
Array Elements Mean: 376.3
Array Elements Median: 236.0
Array Elements Standard Deviation: 529.1366647662965
Array Elements Variance: 279985.61
Array Elements 25th Percentile: 1.25
Array Elements 75th Percentile: 469.75
Array Elements Square Root:


array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 0.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

##### <b> Array Aggregation Methods across Rows or Columns </b></br>&nbsp;&nbsp;axis=0: Aggregate across rows .sum(axis=0) </br> &nbsp;&nbsp;axis=1: Aggregate across columns .sum(axis=1)

In [ ]:
# display sum for rows axis=1
print('Array Row Elements Sum:')
sales_array.sum(axis=1)

Array Row Elements Sum:


array([ 678, 3085])

In [ ]:
# display sum for columns axis=0
print('Array Column Elements Sum:')
sales_array.sum(axis=0)

Array Column Elements Sum:


array([   0,  317,  330,  771, 2345])

##### <b> Sorting Array </b></br> - sort() will sort arrays in place </br> &nbsp;&nbsp; use the axis argument to specify the dimension to sort by

In [ ]:
# copy original sales_array for row and column sorting
sales_array1 = sales_array.copy()
sales_array2 = sales_array.copy()

In [ ]:
# calling sort method will sort multidimensional array row by row as default which is axis=1
sales_array1.sort()
sales_array1

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [ ]:
# to sort by columns use axis=0
sales_array2.sort(axis=0)
sales_array2

array([[   0,    5,  155,    0,  325],
       [   0, 1827,  616,  317,  518]])

In [ ]:
# using np.sort(array_name) will sort but not change order of original array unlike .sort() method
np.sort(sales_array)

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [ ]:
#original sort order of sales_array is maintained
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

#### <b> Broadcasting </b></br> Lets you perform vectorized operations with different sizes, where NumPy will expand the smaller array to 'fit' the larger array <br> Arrays need to have compatible shapes (as long as there is 1 matching dimension)

##### <b> Compatible for Broadcasting </b></br> Array1 (3,3), Array2 (100,3,3) </br> Broadcasting Check: </br> Last dimension: Both arrays have size 3.  </br> Second-last dimension: Both arrays have size 3. </br> First dimension: Array1 has no dimension here, effectively 1, which can be stretched to match 100. </br> Result: Compatible, result shape (100, 3, 3).

##### <b> Not Compatible </b></br> Array1 (4,3), Array2 (100,3,3) </br> Broadcasting Check: </br> Last dimension: Both arrays have size 3. </br> Second-last dimension: Array1 is 4, Array2 is 3. These dimensions are different and neither is 1, so they can't be stretched to match each other. </br> Result: Not compatible. </br>

In [ ]:
test_array = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# even with a scalar value (1) numpy creates a 3x3 array with 1 for each element to add to the test array
test_array + 1

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [ ]:
# when adding a 1d array to a larger dimensional array, the 1d array is added to each row/element 
test_array + np.array([3, 2, 1])
# this is what happens
#[[1+3, 2+2, 3+1],
# [1+3, 2+2, 3+1],
# [1+3, 2+2, 3+1]]


array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
# when adding a 1d array to a larger dimensional array, the 1d array is added to each row/element 
test_array + np.array([3, 2, 1]).reshape(3,1)
# this is what happens
#[[1+3, 2+3, 3+3],
# [1+2, 2+2, 3+2],
# [1+1, 2+1, 3+1]]


array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])

In [ ]:
# can also broadcast between a row and a column dependding on shape
test_array[0, :] + test_array[:, 1] .reshape(3,1)
# this is what happens
# [[1+2, 2+2, 3+2],
#  [1+2, 2+2, 3+2],
#  [1+2, 2+2, 3+2]]

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [ ]:
# adding a 3d array to a 1d array
# 2 nested arrays each with 3 rows and 3 columns being added to 1d array
np.ones((2, 3, 3), 'int') + np.ones((3), 'int')
# [[[1+1, 1+1, 1+1],
#   [1+1, 1+1, 1+1],
#   [1+1, 1+1, 1+1]],

#  [[1+1, 1+1, 1+1],
#   [1+1, 1+1, 1+1],
#   [1+1, 1+1, 1+1]]]

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])