#### NumPy Array Creation

In [2]:
import numpy as np
import pandas as pd

##### <b> Alternative to Converting lists is to create arrays using functions</b></br> - ones: Creates an array of ones of a given size, as float by default </br> &nbsp;&nbsp; np.ones((rows,cols),dtype) </br> - zeros: Creates an array of zeros of a given size, as float by default </br> &nbsp;&nbsp; np.zeros((rows,cols),dtype) </br> - arange: creates an array of integers with a start, stop, step size (only stop is required, and not included) </br> &nbsp;&nbsp; np.arange(start, stop, step) </br> - linspace: creates an array of floats with a start, stop value where the step will be decided by the quantity of n elements (stop value is included) </br> &nbsp;&nbsp; np.linspace(start, stop, n) </br> - reshape: changes an array into the specified dimension (if compatible) </br> &nbsp;&nbsp; np.array.reshape(rows,cols)

In [13]:
# np.ones((rows,cols),dtype)
np.ones(4,)

array([1., 1., 1., 1.])

In [15]:
# np.zeros((rows,cols),dtype)
np.zeros((2, 5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
# np.arange(start,stop,step)
# default start = 1, default step = 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# np.arange(start,stop,step)
# set start, set step
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [24]:
# np.linspace(start,stop,n)
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [25]:
# np.array.reshape(rows,cols)
np.arange(1, 9, 2).reshape(2, 2)

array([[1, 3],
       [5, 7]])

In [27]:
# np.ones((rows,cols),dtype) can have dtype explicitly set instead of default float
np.ones(4,'int') # or use np.ones(4, dtype='int')

array([1, 1, 1, 1])

In [28]:
# np.zeros((rows,cols),dtype)
np.zeros(100, 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
# with reshape for np.zeros(100) the reshape values must be multiply by each other to equal 100 to be compatible
reshapedemo = np.zeros(100, 'int')
reshapedemo.reshape(5,20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
# with reshape for np.zeros(100) the reshape values must be multiply by each other to equal 100 to be compatible
reshapedemo.reshape(2, 50)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

In [35]:
# np.linspace(start,stop,n) for evenly spaced intervals
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

##### <b> Random Number Generation</b></br> Can create random number arrays from variety of distributions using numpy functions and methods </br> - default_rng: Creates a random number generator and seed is used for reproducibility </br> &nbsp;&nbsp; np.default_rng(seed) </br> - random: returns n random numbers from a uniform distributions between 0 and 1 </br> &nbsp;&nbsp; rng.random(n) </br> - normal: returns n random numbers from a normal distribution with a given mean and standard deviation </br> &nbsp;&nbsp; rng.normal(mean,stdev,n)

In [36]:
# Import the default random number generator from NumPy.
from numpy.random import default_rng

# Initialize the random number generator with a specific seed for reproducibility.
rng = default_rng(12345)

# Generate an array of 10 random numbers between 0 and 1.
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [41]:
rng.integers(0, 10, 100)

array([7, 2, 9, 9, 7, 6, 1, 0, 2, 4, 0, 8, 4, 6, 2, 3, 1, 7, 7, 2, 7, 0,
       3, 1, 7, 3, 4, 4, 4, 2, 5, 8, 4, 1, 0, 1, 0, 0, 1, 5, 8, 8, 6, 6,
       3, 9, 6, 7, 7, 8, 7, 9, 5, 5, 2, 9, 5, 4, 3, 2, 6, 4, 5, 6, 8, 3,
       6, 9, 4, 2, 2, 3, 6, 2, 8, 3, 0, 0, 0, 6, 3, 2, 6, 0, 5, 6, 0, 1,
       3, 3, 9, 4, 6, 1, 8, 2, 7, 4, 4, 4], dtype=int64)

In [40]:
# Create a random number generator seeded with 12345 for consistent results.
rng = default_rng(12345)

# Set the mean and standard deviation for the normal distribution.
mean, stddev = 5, 1

# Generate an array of 10 random numbers from a normal distribution with specified mean and stddev.
random_normal = rng.normal(mean, stddev, size=10)
random_normal


array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [42]:
rng.normal(50, 5, 10)

array([49.64364597, 52.37024865, 47.92573119, 50.4885825 , 41.79791082,
       45.71370588, 53.44140894, 44.22735208, 53.25226195, 43.05820024])