#### <b> Broadcasting </b></br> Lets you perform vectorized operations with different sizes, where NumPy will expand the smaller array to 'fit' the larger array <br> Arrays need to have compatible shapes (as long as there is 1 matching dimension)

In [3]:
import numpy as np
import pandas as pd

##### <b> Compatible for Broadcasting </b></br> Array1 (3,3), Array2 (100,3,3) </br> Broadcasting Check: </br> Last dimension: Both arrays have size 3.  </br> Second-last dimension: Both arrays have size 3. </br> First dimension: Array1 has no dimension here, effectively 1, which can be stretched to match 100. </br> Result: Compatible, result shape (100, 3, 3).

##### <b> Not Compatible </b></br> Array1 (4,3), Array2 (100,3,3) </br> Broadcasting Check: </br> Last dimension: Both arrays have size 3. </br> Second-last dimension: Array1 is 4, Array2 is 3. These dimensions are different and neither is 1, so they can't be stretched to match each other. </br> Result: Not compatible. </br>

In [6]:
test_array = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
# even with a scalar value (1) numpy creates a 3x3 array with 1 for each element to add to the test array
test_array + 1

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [11]:
# when adding a 1d array to a larger dimensional array, the 1d array is added to each row/element 
test_array + np.array([3, 2, 1])
# this is what happens
#[[1+3, 2+2, 3+1],
# [1+3, 2+2, 3+1],
# [1+3, 2+2, 3+1]]


array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [14]:
# when adding a 1d array to a larger dimensional array, the 1d array is added to each row/element 
test_array + np.array([3, 2, 1]).reshape(3,1)
# this is what happens
#[[1+3, 2+3, 3+3],
# [1+2, 2+2, 3+2],
# [1+1, 2+1, 3+1]]


array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])

In [16]:
# can also broadcast between a row and a column dependding on shape
test_array[0, :] + test_array[:, 1] .reshape(3,1)
# this is what happens
# [[1+2, 2+2, 3+2],
#  [1+2, 2+2, 3+2],
#  [1+2, 2+2, 3+2]]

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [17]:
# adding a 3d array to a 1d array
# 2 nested arrays each with 3 rows and 3 columns being added to 1d array
np.ones((2, 3, 3), 'int') + np.ones((3), 'int')
# [[[1+1, 1+1, 1+1],
#   [1+1, 1+1, 1+1],
#   [1+1, 1+1, 1+1]],

#  [[1+1, 1+1, 1+1],
#   [1+1, 1+1, 1+1],
#   [1+1, 1+1, 1+1]]]

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])