##### <b> Array Operations </b></br>

##### <b> Arithmetic operators can be used to perform array operations </b></br> - Array operations are applied via vectorization and broadcasting which eliminates need to loop through arrays elements

In [22]:
import numpy as np
import pandas as pd

In [23]:
# generate nested list
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]

# convert in np array
sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [24]:
# with + 2 -> 2 is added to each element of the np array
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [25]:
# Assign all elements of first row to quantity
quantity = sales_array[0, :]
# Assign all elements of second row to price
price = sales_array[1, :]

# corresponding elements are multiplied together
quantity * price

array([     0,   9135,  95480,      0, 168350])

In [26]:
# generate random number generator with 616 seed
rng = np.random.default_rng(616)

# assign random integers to inventory variable start 0, end 100, 10 random grabbed
inventory = rng.integers(0, 100, 10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [27]:
# minus 24 from each array element
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [28]:
# view half the inventory amounts -> divide 2 from each array element
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [29]:
# create 11 random price values (which will be between 0 and 1) so multiple by 10 and then round to 2 decimal places
# price = (rng.random(11)*10).round(2)
# this operation will have error because array shapes do not match 10 vs 11
# price * inventory

In [30]:
# create 10 random price values (which will be between 0 and 1) so multiple by 10 and then round to 2 decimal places
price = (rng.random(10)*10).round(2)

price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [32]:
# operations can occurs between arrays as long as they are the same shape
# price * inventory

# the is a sum method to easily add all element values
(price * inventory).sum().round(2)

2520.47

In [34]:
# np arrays can be cast to a list
inventory_list = list(inventory)
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

##### <b> Filtering Arrays </b></br> You can filter arrays by indexing them with a logical test </br> - Only the array elements in positions where the logical test returns True are returned

In [35]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])