#### NumPy Array Basics

In [2]:
import numpy as np
import pandas as pd

##### Numpy Arrays are fixed-sized containers </br> - Store only 1 datatype, (mixed are object -string) </br> - 1 dimensional or multidimensional </br> - Array elements can be modified, but array size cannot change

In [3]:
## List to numpy array example
# List
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
# np function will convert list as numpy array
sales_array = np.array(sales, dtype = np.int64)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325],
      dtype=int64)

##### Numpy Arrays Key Properties </br> - ndim: Number of dimensions (axes) in array </br> - shape: size of array for each dimension </br> - size: total number of elements in array </br> - dtype: data type of elements in array

In [4]:
# display type of array
type(sales_array)
# numpy arrays are ndarray Python Data type: stands for n-dimensional array

numpy.ndarray

In [5]:
# display different aspects of numpy sales_array
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")

ndim: 1
shape: (10,)
size: 10
dtype: int64


In [6]:
# ndim: 1      -> Array has 1 dimension
# shape: (10,) -> Dimension has a size of 10
# size: 10     -> Array has 10 elements in total
# dtype: int64 -> Elements stored as 64-bit Integers

In [7]:
# Original lists has nested elements which means [[],[]] is the format
# nested lists must be of equal length
sales2d = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
# np function will convert nested list as numpy array as dtype4 int64
sales2d_array = np.array(sales2d, dtype = np.int64)
sales2d_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]], dtype=int64)

In [8]:
# display different aspects of numpy sales2d_arrays 
print(f"ndim: {sales2d_array.ndim}")
print(f"shape: {sales2d_array.shape}")
print(f"size: {sales2d_array.size}")
print(f"dtype: {sales2d_array.dtype}")

ndim: 2
shape: (2, 5)
size: 10
dtype: int64


In [9]:
# ndim: 2      -> Array has 2 dimension
# shape: (2, 5)-> First Dimension has size 2 (rows), Second Dimension has Size of 5 (columns)
# size: 10     -> Array has 10 elements in total
# dtype: int64 -> Elements stored as 64-bit Integers

In [10]:
# Create 1d numpy array using range function
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [11]:
# Create 1d numpy array using range function
array2d = np.array([range(5), range(5)])
array2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [12]:
np.array(['I', 'Love', 'Python'])
# displays dtype as '<U6' because strings are max of 6 characters

array(['I', 'Love', 'Python'], dtype='<U6')